# Generated by Django 3.1 on 2021-05-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nthapp', '0011_auto_20210523_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image1',
            field=models.URLField(default=None, max_length=2083),
        ),
        migrations.AlterField(
            model_name='question',
            name='image2',
            field=models.URLField(default=None, max_length=2083),
        ),
        migrations.AlterField(
            model_name='question',
            name='image3',
            field=models.URLField(default=None, max_length=2083),
        ),
        migrations.AlterField(
            model_name='question',
            name='image4',
            field=models.URLField(default=None, max_length=2083),
        ),
    ]
