# Generated by Django 3.2 on 2021-05-19 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latest_que_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 12, 28, 48, 511047)),
        ),
    ]
