# Generated by Django 3.2 on 2021-05-19 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_profile_latest_que_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ans',
            new_name='correct_ans',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='user_response',
            new_name='attempt',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_attempted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_que_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 13, 16, 36, 317973)),
        ),
    ]
