# Generated by Django 3.2 on 2021-05-19 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210519_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_que_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 13, 28, 26, 640065)),
        ),
    ]
