# Generated by Django 3.2 on 2021-05-20 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210519_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_rem',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_que_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 20, 23, 14, 35, 676893)),
        ),
    ]
