# Generated by Django 3.2 on 2021-05-23 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210523_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ques_no',
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_que_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 23, 16, 5, 15, 586470)),
        ),
    ]
