# Generated by Django 3.2 on 2021-05-23 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210523_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_que_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 23, 16, 34, 34, 860663)),
        ),
    ]
