# Generated by Django 3.2 on 2021-05-23 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210523_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_question_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_que_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 23, 16, 50, 20, 863451)),
        ),
    ]
