# Generated by Django 3.2 on 2021-05-23 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210523_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='number_of_question_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='time_rem',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_que_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 23, 20, 18, 31, 811488)),
        ),
    ]
