# Generated by Django 3.2 on 2021-05-23 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210523_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='latest_que_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 23, 21, 54, 9, 338958)),
        ),
    ]
