# Generated by Django 3.2 on 2021-04-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='lol', max_length=100, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('fullname', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default=None, max_length=50)),
                ('college', models.TextField(default='N/A')),
                ('mobile_number', models.BigIntegerField(default=0, verbose_name='Phone Number')),
                ('level', models.IntegerField(db_index=True, default=1)),
                ('logout_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='N/A', max_length=300)),
                ('answer', models.CharField(default='N/A', max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('tips', models.TextField(default='N/A', max_length=100)),
            ],
        ),
    ]
