# Generated by Django 3.2 on 2021-04-26 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nthapp', '0005_alter_playme_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playme',
            name='fullname',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='playme',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
