# Generated by Django 3.2 on 2021-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nthapp', '0013_auto_20210613_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image1',
            field=models.URLField(default=None, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image2',
            field=models.URLField(default=None, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image3',
            field=models.URLField(default=None, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image4',
            field=models.URLField(default=None, max_length=2083, null=True),
        ),
    ]
