# Generated by Django 3.2 on 2021-04-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playme',
            options={'verbose_name': 'Play Me'},
        ),
    ]
