# Generated by Django 3.2 on 2021-04-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nthapp', '0002_alter_playme_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playme',
            name='password',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
    ]
