# Generated by Django 3.2 on 2021-04-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nthapp', '0004_alter_playme_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playme',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
