# Generated by Django 3.1 on 2021-05-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nthapp', '0008_alter_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image3',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='playme',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
